#! /bin/sh
chmod -x img/*.jpg img/weather/*.jpg *.pdf *.ltx xepersian.dtx
xelatex xepersian.dtx
xelatex xepersian.dtx
makeindex -s gind.ist -o xepersian.ind  xepersian.idx
makeindex -s gglo.ist -o xepersian.gls  xepersian.glo
xelatex xepersian.dtx
teckit_compile persian-tex-text.map
teckit_compile persian-tex-text.map
teckit_compile persian-tex-text.map
xelatex xepersian-doc.ltx
xelatex xepersian-doc.ltx
xelatex xepersian-doc.ltx
mkdir -p doc/xelatex/xepersian fonts/misc/xetex/fontmapping/xepersian source/xelatex/xepersian tex/xelatex/xepersian 
mkdir xepersian
mv *.def *.sty *.cls tex/xelatex/xepersian
cp *.ltx *.dtx *.ins  xepersian-logo.pdf source/xelatex/xepersian
cp -r xepersian.pdf xepersian-doc.pdf *.py *.tex README.txt img doc/xelatex/xepersian
mv persian-tex-text.map persian-tex-text.tec fonts/misc/xetex/fontmapping/xepersian
zip -r xepersian.tds.zip doc/xelatex/xepersian fonts/misc/xetex/fontmapping/xepersian source/xelatex/xepersian tex/xelatex/xepersian
mv doc/xelatex/xepersian/*.pdf doc/xelatex/xepersian/*.py doc/xelatex/xepersian/README.txt  doc/xelatex/xepersian/img source/xelatex/xepersian/*.ltx source/xelatex/xepersian/*.dtx  xepersian
zip -r xepersian-ctan.zip xepersian.tds.zip xepersian
rm -r doc tex source fonts xepersian
rm *.aux  *.hd *.idx *.ilg *.ind *.log *.out *.toc xepersian.tds.zip
rm     magazine-sample.tex test*tex xepersian-logo.tex xepersian.ins README.txt
